//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutPacker.SpriteSheet
{
    
    public class TestContent : NutPacker.ISpriteSheet
    {
        public class Stickers : NutPacker.ISpriteSheet
        {
            public class Homer : NutPacker.Sprite
            {
                public Homer()
                {
                    this.Frames = new System.Drawing.Rectangle[] {
                            new System.Drawing.Rectangle(2048, 3072, 192, 192),
                            new System.Drawing.Rectangle(1536, 3776, 192, 192),
                            new System.Drawing.Rectangle(3264, 2048, 192, 192),
                            new System.Drawing.Rectangle(2048, 3264, 192, 192),
                            new System.Drawing.Rectangle(2240, 3072, 192, 192),
                            new System.Drawing.Rectangle(2432, 3072, 192, 192),
                            new System.Drawing.Rectangle(2240, 3264, 192, 192),
                            new System.Drawing.Rectangle(1920, 3584, 192, 192),
                            new System.Drawing.Rectangle(1728, 3776, 192, 192),
                            new System.Drawing.Rectangle(1536, 3584, 192, 192),
                            new System.Drawing.Rectangle(3072, 2048, 192, 192),
                            new System.Drawing.Rectangle(2560, 2560, 192, 192),
                            new System.Drawing.Rectangle(3072, 2240, 192, 192),
                            new System.Drawing.Rectangle(2752, 2560, 192, 192),
                            new System.Drawing.Rectangle(2560, 2752, 192, 192),
                            new System.Drawing.Rectangle(1728, 3584, 192, 192)};
                }
            }
            public class People : NutPacker.Sprite
            {
                public People()
                {
                    this.Frames = new System.Drawing.Rectangle[] {
                            new System.Drawing.Rectangle(0, 0, 512, 512),
                            new System.Drawing.Rectangle(1024, 1024, 512, 512),
                            new System.Drawing.Rectangle(2560, 1024, 512, 512),
                            new System.Drawing.Rectangle(512, 2048, 512, 512),
                            new System.Drawing.Rectangle(512, 3584, 512, 512),
                            new System.Drawing.Rectangle(1024, 3584, 512, 512),
                            new System.Drawing.Rectangle(2048, 2560, 512, 512),
                            new System.Drawing.Rectangle(1536, 3072, 512, 512),
                            new System.Drawing.Rectangle(2560, 2048, 512, 512),
                            new System.Drawing.Rectangle(512, 0, 512, 512),
                            new System.Drawing.Rectangle(0, 512, 512, 512),
                            new System.Drawing.Rectangle(512, 512, 512, 512),
                            new System.Drawing.Rectangle(1024, 0, 512, 512),
                            new System.Drawing.Rectangle(1024, 512, 512, 512),
                            new System.Drawing.Rectangle(1536, 0, 512, 512),
                            new System.Drawing.Rectangle(1536, 512, 512, 512),
                            new System.Drawing.Rectangle(0, 1024, 512, 512),
                            new System.Drawing.Rectangle(0, 1536, 512, 512),
                            new System.Drawing.Rectangle(512, 1024, 512, 512),
                            new System.Drawing.Rectangle(512, 1536, 512, 512),
                            new System.Drawing.Rectangle(1024, 1536, 512, 512),
                            new System.Drawing.Rectangle(1536, 1024, 512, 512),
                            new System.Drawing.Rectangle(1536, 1536, 512, 512),
                            new System.Drawing.Rectangle(2048, 0, 512, 512),
                            new System.Drawing.Rectangle(2560, 0, 512, 512),
                            new System.Drawing.Rectangle(2048, 512, 512, 512),
                            new System.Drawing.Rectangle(3072, 0, 512, 512),
                            new System.Drawing.Rectangle(2560, 512, 512, 512),
                            new System.Drawing.Rectangle(2048, 1024, 512, 512),
                            new System.Drawing.Rectangle(2048, 1536, 512, 512),
                            new System.Drawing.Rectangle(3072, 512, 512, 512),
                            new System.Drawing.Rectangle(3584, 0, 512, 512),
                            new System.Drawing.Rectangle(3584, 512, 512, 512),
                            new System.Drawing.Rectangle(3072, 1024, 512, 512),
                            new System.Drawing.Rectangle(2560, 1536, 512, 512),
                            new System.Drawing.Rectangle(3072, 1536, 512, 512),
                            new System.Drawing.Rectangle(3584, 1024, 512, 512),
                            new System.Drawing.Rectangle(3584, 1536, 512, 512),
                            new System.Drawing.Rectangle(0, 2048, 512, 512),
                            new System.Drawing.Rectangle(0, 2560, 512, 512),
                            new System.Drawing.Rectangle(512, 2560, 512, 512),
                            new System.Drawing.Rectangle(0, 3072, 512, 512),
                            new System.Drawing.Rectangle(1024, 2048, 512, 512),
                            new System.Drawing.Rectangle(512, 3072, 512, 512),
                            new System.Drawing.Rectangle(0, 3584, 512, 512),
                            new System.Drawing.Rectangle(1024, 2560, 512, 512),
                            new System.Drawing.Rectangle(1536, 2048, 512, 512),
                            new System.Drawing.Rectangle(2048, 2048, 512, 512),
                            new System.Drawing.Rectangle(1024, 3072, 512, 512),
                            new System.Drawing.Rectangle(1536, 2560, 512, 512)};
                }
            }
        }
    }
}
